version: '3.6'

services:

#  db:
#    image: postgres:14.4-alpine
#    restart: always
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#    env_file:
#      - ./.env

  bot:
    build: ../bot/
    restart: always

#volumes:
#  postgres_data: